spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3307/tub_pgu
spring.datasource.username=devuser
spring.datasource.password=devpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
